language: node_js
node_js:
  - 13

services:
  - docker

# Scripts to be run such as test
before_script:
  - echo "Travis Run Project 3"

script:



- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker tag udagram-api-feed toumi213/udagram-api-feed:v1
- docker tag udagram-api-user toumi213/udagram-api-user:v1
- docker tag udagram-frontend toumi213/udagram-frontend:v1
- docker tag udagram-reverseproxy toumi213/udagram-reverseproxy:v1
after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push toumi213/udagram-api-feed:v1
- docker push toumi213/udagram-api-user:v1
- docker push toumi213/udagram-frontend:v1
- docker push toumi213/udagram-reverseproxy:v1
